### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by omerm2001** [Glarity/reddit2instagrambot#17]
Request return 400 error!
{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/6469404380/BOXa7zRuxg/', 'api_path': '/challenge/6469404380/BOXa7zRuxg/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main(args)
  File "main.py", line 17, in main
    downloadAndUpload()
  File "main.py", line 25, in downloadAndUpload
    instagram.upload_subs(found_subs)
  File "/root/reddit2instagrambot/reddit2instagram/instagram.py", line 29, in upload_subs
    instagram_api.uploadPhoto(os.path.join(BASE_DIR, "media", sub["id"] + "_resized" + sub["format"]), caption=sub_caption)
  File "/usr/local/lib/python3.6/site-packages/InstagramAPI/InstagramAPI.py", line 146, in uploadPhoto
    '_csrftoken': self.token,
**AttributeError: 'InstagramAPI' object has no attribute 'token'**

If there is any chance you can help it'll be great. Thanks in advance.

**Comment by tylerolson** [comment]
The Instagram API is no longer working so I will need to remake the project using a different method. Nothing you can do right now :/
